# PostgreSQL version 9.x
#   gem install pg
#
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30
  reaping_frequency: 10
  application_name: payments_service

development: &development
  <<: *default
  database: <%= ENV['LOCAL_DB_NAME'] || 'payments_service' %>
  username: <%= ENV['LOCAL_DB_USER'] || '' %>
  password: <%= ENV['LOCAL_DB_PASSWORD'] || '' %>
  host: <%= ENV['LOCAL_DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['LOCAL_DB_PORT'] || 5432 %>
  gssencmode: disable
production:
  <<: *default
  database: <%= ENV['LOCAL_DB_NAME'] || 'mykhailo' %>
  username: <%= ENV['LOCAL_DB_USER']%>
  password:  <%= ENV['LOCAL_DB_PASSWORD'] %>
  host:  <%= ENV['LOCAL_DB_HOST'] %>

test:
  <<: *development
  database: payments_service
  gssencmode: disable